Repository JNU-econovation/Dotoring-BE, pull requests merged in 2023-07, with the labels that each got.

#32 [#29] Letter 병합 및 MentoLetter와 MentiLetter로 분리
  .idea/compiler.xml
  build.gradle
  src/main/java/com/theZ/dotoring/app/letter/controller/LetterFromMentiController.java
  src/main/java/com/theZ/dotoring/app/letter/controller/LetterFromMentoController.java
  src/main/java/com/theZ/dotoring/app/letter/domain/Letter.java
  src/main/java/com/theZ/dotoring/app/letter/dto/LetterByMemberRequestDTO.java
  src/main/java/com/theZ/dotoring/app/letter/dto/LetterByMemberResponseDTO.java
  src/main/java/com/theZ/dotoring/app/letter/dto/LettersAndMemberDTO.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/CreateLetterByMentiHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/CreateMentiLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/GetMentiLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/GetRoomByMentiHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/CreateLetterByMentoHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/CreateMentoLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/GetMentoLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/GetRoomByMentoHandler.java
  src/main/java/com/theZ/dotoring/app/letter/mapper/LetterMapper.java
  src/main/java/com/theZ/dotoring/app/letter/repository/LetterRepository.java
  src/main/java/com/theZ/dotoring/app/letter/service/LetterMentiService.java
  src/main/java/com/theZ/dotoring/app/letter/service/LetterMentoService.java
  src/main/java/com/theZ/dotoring/app/room/domain/Room.java
  src/main/java/com/theZ/dotoring/app/room/dto/RoomResponseDTO.java
  src/main/java/com/theZ/dotoring/app/room/mapper/RoomMapper.java
  src/main/java/com/theZ/dotoring/app/room/repository/RoomRepository.java
  src/main/java/com/theZ/dotoring/app/room/service/RoomService.java
  src/test/java/com/theZ/dotoring/DotoringApplicationTests.java
  src/test/java/com/theZ/dotoring/controller/ControllerTest.java
Labels: enhancement

#39 [#36] 병합 후 initializationError 해결
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/com.theZ.dotoring.main.iml
  .idea/modules/dotoring.main.iml
  build.gradle
  build/generated/'querydsl'/generated/com/theZ/dotoring/app/letter/mapper/LetterMapperImpl.java
  build/generated/'querydsl'/generated/com/theZ/dotoring/app/room/mapper/RoomMapperImpl.java
  src/main/java/com/theZ/dotoring/app/menti/dto/MentiCardResponseDTO.java
  src/main/java/com/theZ/dotoring/app/menti/dto/MentiSignupRequestDTO.java
  src/main/java/com/theZ/dotoring/app/menti/mapper/MentiMapper.java
  src/main/java/com/theZ/dotoring/app/mento/dto/MentoSignupRequestDTO.java
  src/test/java/com/theZ/dotoring/controller/ControllerTest.java
Labels: bug

#45 [#42] 멘토 필터 기능 구현
  build/generated/'querydsl'/generated/com/theZ/dotoring/app/letter/mapper/LetterMapperImpl.java
  build/generated/'querydsl'/generated/com/theZ/dotoring/app/room/mapper/RoomMapperImpl.java
  src/main/java/com/theZ/dotoring/app/letter/controller/LetterFromMentiController.java
  src/main/java/com/theZ/dotoring/app/member/mapper/MemberMapper.java
  src/main/java/com/theZ/dotoring/app/menti/handler/FindAllMentiHandler.java
  src/main/java/com/theZ/dotoring/app/menti/model/MentiFilterCondition.java
  src/main/java/com/theZ/dotoring/app/menti/repository/MentiQueryRepository.java
  src/main/java/com/theZ/dotoring/app/menti/service/MentiService.java
  src/main/java/com/theZ/dotoring/app/mento/controller/MentoController.java
  src/main/java/com/theZ/dotoring/app/mento/dto/MentoRequiredCondition.java
  src/main/java/com/theZ/dotoring/app/mento/handler/FindAllMentoHandler.java
  src/main/java/com/theZ/dotoring/app/mento/model/MentoFilterCondition.java
  src/main/java/com/theZ/dotoring/app/mento/repository/MentoQueryRepository.java
  src/main/java/com/theZ/dotoring/app/mento/service/MentoService.java
  src/main/java/com/theZ/dotoring/common/DefaultCondition.java
  src/main/java/com/theZ/dotoring/enums/Job.java
  src/main/java/com/theZ/dotoring/enums/Major.java
Labels: enhancement

#47 [#42] 회원 상세 조회 기능 + 인덱스
  src/main/java/com/theZ/dotoring/app/member/model/Member.java
  src/main/java/com/theZ/dotoring/app/menti/controller/MentiController.java
  src/main/java/com/theZ/dotoring/app/menti/dto/MentiCardResponseDTO.java
  src/main/java/com/theZ/dotoring/app/menti/mapper/MentiMapper.java
  src/main/java/com/theZ/dotoring/app/mento/controller/MentoController.java
  src/main/java/com/theZ/dotoring/app/mento/dto/MentoCardResponseDTO.java
  src/main/java/com/theZ/dotoring/app/mento/mapper/MentoMapper.java
Labels: enhancement

#55 [#53] Letter 커스텀 에러 구현 및 핸들링
  .gradle/7.6.1/executionHistory/executionHistory.bin
  .gradle/7.6.1/executionHistory/executionHistory.lock
  .gradle/7.6.1/fileHashes/fileHashes.bin
  .gradle/7.6.1/fileHashes/fileHashes.lock
  .gradle/7.6.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/generated/sources/annotationProcessor/java/main/com/theZ/dotoring/app/letter/mapper/LetterMapperImpl.java
  build/tmp/compileJava/compileTransaction/stash-dir/CreateLetterByMentiHandler.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/CreateLetterByMentoHandler.class.uniqueId14
  build/tmp/compileJava/compileTransaction/stash-dir/CreateMentiLetterByRoomHandler.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/CreateMentoLetterByRoomHandler.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/FindAllMentiHandler.class.uniqueId11
  build/tmp/compileJava/compileTransaction/stash-dir/FindAllMentoHandler.class.uniqueId17
  build/tmp/compileJava/compileTransaction/stash-dir/GetMentiLetterByRoomHandler.class.uniqueId16
  build/tmp/compileJava/compileTransaction/stash-dir/GetMentoLetterByRoomHandler.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/GetRoomByMentiHandler.class.uniqueId12
  build/tmp/compileJava/compileTransaction/stash-dir/GetRoomByMentoHandler.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/GlobalExceptionHandler.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/LetterFromMentiController.class.uniqueId13
  build/tmp/compileJava/compileTransaction/stash-dir/LetterFromMentoController.class.uniqueId15
  build/tmp/compileJava/compileTransaction/stash-dir/MentiController.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/MentiQueryRepository.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/MentiService.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/MentoController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/RoomService.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/SaveMentiHandler.class.uniqueId9
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/theZ/dotoring/app/letter/controller/LetterFromMentiController.java
  src/main/java/com/theZ/dotoring/app/letter/controller/LetterFromMentoController.java
  src/main/java/com/theZ/dotoring/app/letter/dto/LetterByMemberRequestDTO.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/GetMentiLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/GetRoomByMentiHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/GetMentoLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/GetRoomByMentoHandler.java
  src/main/java/com/theZ/dotoring/app/letter/service/LetterMentiService.java
  src/main/java/com/theZ/dotoring/app/letter/service/LetterMentoService.java
  src/main/java/com/theZ/dotoring/app/room/service/RoomService.java
  src/main/java/com/theZ/dotoring/common/MessageCode.java
  src/main/java/com/theZ/dotoring/exception/ExtentionNotAllowedException.java
  src/main/java/com/theZ/dotoring/exception/GlobalExceptionHandler.java
  src/main/java/com/theZ/dotoring/exception/NotFoundLetterException.java
  src/main/java/com/theZ/dotoring/exception/NotFoundRoomException.java
Labels: enhancement

#59 [#56] 노션 API 문서 최신화 및 Room 조회 에러 수정
  .gradle/7.6.1/executionHistory/executionHistory.bin
  .gradle/7.6.1/executionHistory/executionHistory.lock
  .gradle/7.6.1/fileHashes/fileHashes.bin
  .gradle/7.6.1/fileHashes/fileHashes.lock
  .gradle/7.6.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/generated/sources/annotationProcessor/java/main/com/theZ/dotoring/app/room/mapper/RoomMapperImpl.java
  build/tmp/compileJava/compileTransaction/stash-dir/CreateLetterByMentiHandler.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/CreateLetterByMentoHandler.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/CreateMentiLetterByRoomHandler.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/CreateMentoLetterByRoomHandler.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/GetMentiLetterByRoomHandler.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/GetMentoLetterByRoomHandler.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/GetRoomByMentiHandler.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/GetRoomByMentoHandler.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/GlobalExceptionHandler.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/LetterFromMentiController.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/LetterFromMentoController.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/RoomService.class.uniqueId3
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/theZ/dotoring/app/letter/controller/LetterFromMentiController.java
  src/main/java/com/theZ/dotoring/app/letter/controller/LetterFromMentoController.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/GetRoomByMentiHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/GetRoomByMentoHandler.java
  src/main/java/com/theZ/dotoring/app/room/dto/RoomResponseDTO.java
  src/main/java/com/theZ/dotoring/app/room/mapper/RoomMapper.java
  src/main/java/com/theZ/dotoring/app/room/service/RoomService.java
Labels: bug, documentation, enhancement

#60 [#51] 회원가입시 증명서 저장 흐름 변경
  src/main/java/com/theZ/dotoring/app/certification/controller/CertificationController.java
  src/main/java/com/theZ/dotoring/app/certification/service/CertificationService.java
  src/main/java/com/theZ/dotoring/app/member/controller/MemberController.java
  src/main/java/com/theZ/dotoring/app/member/controller/MemberManagerController.java
  src/main/java/com/theZ/dotoring/app/member/dto/MemberEmailRequestDTO.java
  src/main/java/com/theZ/dotoring/app/member/dto/MemberInfoResponseDTO.java
  src/main/java/com/theZ/dotoring/app/member/dto/MemberJobAndMajorResponseDTO.java
  src/main/java/com/theZ/dotoring/app/member/dto/MemberLoginIdRequestDTO.java
  src/main/java/com/theZ/dotoring/app/member/dto/MemberNicknameRequestDTO.java
  src/main/java/com/theZ/dotoring/app/menti/controller/MentiController.java
  src/main/java/com/theZ/dotoring/app/menti/dto/MentiSignupRequestDTO.java
  src/main/java/com/theZ/dotoring/app/menti/handler/SaveMentiHandler.java
  src/main/java/com/theZ/dotoring/app/mento/controller/MentoController.java
  src/main/java/com/theZ/dotoring/app/mento/dto/MentoSignupRequestDTO.java
  src/main/java/com/theZ/dotoring/app/mento/handler/SaveMentoHandler.java
  src/main/java/com/theZ/dotoring/app/mento/service/MentoService.java
  src/main/java/com/theZ/dotoring/enums/Job.java
  src/main/java/com/theZ/dotoring/enums/Major.java
Labels: enhancement

#71 [#69] Room API 중 학과 API 추가
  build/generated/'querydsl'/generated/com/theZ/dotoring/app/letter/mapper/LetterMapperImpl.java
  build/generated/'querydsl'/generated/com/theZ/dotoring/app/room/mapper/RoomMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/theZ/dotoring/app/letter/mapper/LetterMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/theZ/dotoring/app/room/mapper/RoomMapperImpl.java
  gradlew
  src/main/java/com/theZ/dotoring/app/room/dto/RoomResponseDTO.java
  src/main/java/com/theZ/dotoring/app/room/mapper/RoomMapper.java
Labels: enhancement

#77 [#76] Room Mock data updateAt 필드 누락 수정
  src/main/java/com/theZ/dotoring/common/DataInit.java
Labels: bug

#80 [#79] Room Mock 데이터 updateAt 값이 안들어가던 오류 해결
  src/main/java/com/theZ/dotoring/app/menti/controller/MentiController.java
  src/main/java/com/theZ/dotoring/common/DataInit.java
Labels: bug
